#!/bin/sh

# Goes through all jpeg files in current directory, grabs date from each
# and sorts them into subdirectories according to the date
# Creates subdirectories corresponding to the dates as necessary.

for fil in *.jpg  # Also try *.JPG
do
    datepath="$(identify -verbose $fil | grep DateTimeOri | awk '{print $2 }' | sed s%:%/%g)"
    echo $datepath
    if ! test -e "$datepath"; then
	echo "Creating dir:"$datepath
        #mkdir -pv "$datepath"
    fi
    echo "Moving file..."
#    mv -v $fil $datepath
done
